export const projects = [
  {
    name: "The Wild Oasis",
    image: "the-wild-oasis.png",
    about: "A hotel management web app",
    tech: "react,supabase",
    webApp: "https://the-wild-oasis-mgmt.vercel.app",
    demoVideo: "https://youtu.be/vajksh7zW9M",
    sourceCode: "https://github.com/jominjose14/the-wild-oasis",
  },
  {
    name: "SleepyWheels",
    image: "sleepywheels.jpg",
    about: "An app that detects & sounds an alarm when the driver falls asleep",
    tech: "keras,efficientnetv2,python,php,mysql",
    webApp: "http://jominjose.42web.io/dashboard.php?i=1",
    demoVideo: "https://www.youtube.com/watch?v=KaCROQi2XRs",
    sourceCode: "https://github.com/jominjose14/SleepyWheels",
  },
  {
    name: "Mimic",
    image: "mimic.png",
    about: "An app that brings air gesture gaming to Android",
    tech: "android,mlkit",
    demoVideo: "https://youtu.be/F9RwOJvrfzw",
    sourceCode: "https://github.com/jominjose14/Mimic",
  },
  {
    name: "Flame",
    image: "flame.jpg",
    about:
      "Game: escape from a fiery castle full of explosive traps and monsters",
    tech: "unreal engine 5",
    demoVideo: "https://youtu.be/7fJv2bOYd84",
    download:
      "https://drive.google.com/file/d/1qUhjNmYzwxXGe5akgQ0y2EurWHvWqiF4/view?usp=share_link",
  },
  {
    name: "FaceMask",
    image: "facemask.jpg",
    about:
      "A face mask detector build to ensure public safety during an airborne pandemic",
    tech: "python,keras,resnet50,mobilenetv2",
    demoVideo: "https://www.youtube.com/watch?v=DMgSwCbm8EM",
    sourceCode: "https://github.com/jominjose14/FaceMask",
  },
  {
    name: "AI Personal Trainer",
    image: "personal-trainer.jpg",
    about:
      "An AI that monitors angles made during reps to ensure workout quality",
    tech: "python,mediapipe,opencv",
    demoVideo: "https://youtu.be/cy5hFlAnVS8",
    sourceCode: "https://github.com/jominjose14/AI-Personal-Trainer",
  },
  {
    name: "AI plays Flappy Bird",
    image: "neural.png",
    about: "An AI learns to play Flappy Bird through neuro-evolution",
    tech: "python,neat,pygame",
    demoVideo: "https://youtu.be/2E4o2leGtTk",
    sourceCode: "https://github.com/jominjose14/AI-Flappy-Bird",
  },
  {
    name: "Ice",
    image: "ice.png",
    about: "A Twitter-like social media web app",
    tech: "react,nodejs,firebase",
    webApp: "https://ice-app-f7186.web.app",
    sourceCode: "https://github.com/jominjose14/ice",
  },
  {
    name: "Melody",
    image: "melody.png",
    about: "A free online piano game that tests auditory and visual memory",
    tech: "html,css,js",
    webApp: "https://jominjose14.github.io/melody",
    sourceCode: "https://github.com/jominjose14/melody",
  },
  {
    name: "DrumKit 7.0",
    image: "drumkit.jpg",
    about: "A free online drumkit with configurable controls",
    tech: "html,css,js",
    webApp: "https://jominjose14.github.io/drumkit-7.0",
    sourceCode: "https://github.com/jominjose14/drumkit-7.0",
  },
  {
    name: "Lazy Bird",
    image: "lazybird.png",
    about: "An ice-themed remake of the Flappy Bird game",
    tech: "android,java,libgdx",
    demoVideo: "https://www.youtube.com/watch?v=VUkZguVlQK4",
    sourceCode: "https://github.com/jominjose14/LazyBird",
  },
  {
    name: "Muzik",
    image: "muzik.png",
    about: "A minimalistic yet stylish Android music player",
    tech: "android,java",
    demoVideo: "https://www.youtube.com/watch?v=xCsOT1tNK2k",
    sourceCode: "https://github.com/jominjose14/Muzik",
  },
  {
    name: "Tom vs Jerry",
    image: "tom-vs-jerry.jpg",
    about: "A Tom & Jerry themed tick-tac-toe game",
    tech: "android,java",
    demoVideo: "https://youtu.be/O-cqOHBODUI",
    sourceCode: "https://github.com/jominjose14/TicTacToeTomVSJerry",
  },
];
