import type { Project } from "./types";

export const projects: Project[] = [
    {
        name: "Peerpedia",
        image: "peerpedia.svg",
        about: "A barter-learning social media web app with real-time chat",
        tech: "java,springboot,docker,nginx,redis,postgresql,typescript,react",
        webApp: "https://peerpedia.onrender.com",
        demoVideo: "https://youtu.be/sX2uJ_SxOAM",
        sourceCode: "https://github.com/jominjose14/peerpedia",
    },
    {
        name: "Goal",
        image: "goal.svg",
        about: "A real-time online multiplayer air hockey game web app",
        tech: "golang,html canvas,websockets",
        webApp: "https://goal-pb1a.onrender.com",
        demoVideo: "https://youtu.be/B8xrVml8mBA",
        sourceCode: "https://github.com/jominjose14/goal",
    },
    {
        name: "ApparelKart",
        image: "apparelkart.svg",
        about: "E-commerce recommendation engine built from scratch",
        tech: "python,bow,tf-idf,nltk,pandas,flask,typescript",
        webApp: "https://apparelkart.onrender.com",
        demoVideo: "https://youtu.be/J-kAl7L6Tlo",
        sourceCode: "https://github.com/jominjose14/apparelkart",
    },
    {
        name: "SleepyWheels",
        image: "sleepywheels.jpg",
        about: "A driver drowsiness detection system that alerts the driver before they fall asleep",
        tech: "python,cnn,efficientnetv2,keras,node,postgresql",
        webApp: "http://jominjose.42web.io/dashboard.php?i=1",
        demoVideo: "https://www.youtube.com/watch?v=KaCROQi2XRs",
        sourceCode: "https://github.com/jominjose14/SleepyWheels",
    },
    {
        name: "The Wild Oasis",
        image: "the-wild-oasis.png",
        about: "A hotel management web app to manage cabins, bookings & checkouts",
        tech: "react,react-router,tailwindcss,node,postgresql",
        webApp: "https://the-wild-oasis-mgmt.vercel.app",
        demoVideo: "https://youtu.be/vajksh7zW9M",
        sourceCode: "https://github.com/jominjose14/the-wild-oasis",
    },
    {
        name: "Odin Tracker",
        image: "odin-tracker.svg",
        about: "A progress tracker for students of the Odin project (a popular web dev course)",
        tech: "n-ary tree,react,tailwindcss,postgresql",
        webApp: "https://odin-tracker.vercel.app",
        sourceCode: "https://github.com/jominjose14/odin-tracker",
    },
    {
        name: "Ice",
        image: "ice.png",
        about: "A Twitter-like social media web app with an icy theme",
        tech: "react,material-ui,node,firebase,firestore",
        webApp: "https://ice-app-f7186.web.app",
        sourceCode: "https://github.com/jominjose14/ice",
    },
    {
        name: "Mimic",
        image: "mimic.png",
        about: "An app for using Android by making touch-free gestures that are captured by the selfie camera and translated to swipes",
        tech: "java,android,mlkit",
        demoVideo: "https://youtu.be/F9RwOJvrfzw",
        sourceCode: "https://github.com/jominjose14/Mimic",
    },
    {
        name: "Newtritions",
        image: "newtritions.jpg",
        about: "E-commerce web app frontend for fitness and nutrition products",
        tech: "html,css,javascript,wordpress",
        demoVideo: "https://drive.google.com/file/d/1HTtS5vsRIkHweJbTqwX5sGTAzAQB4aJL/view?usp=drive_link",
    },
    {
        name: "Flame",
        image: "flame.jpg",
        about: "An adventure game: escape from a fiery castle full of explosive traps and monsters",
        tech: "unreal engine 5",
        demoVideo: "https://youtu.be/7fJv2bOYd84",
        download: "https://drive.google.com/file/d/1qUhjNmYzwxXGe5akgQ0y2EurWHvWqiF4/view?usp=share_link",
    },
    {
        name: "FaceMask",
        image: "facemask.jpg",
        about: "A face mask detector built to ensure public safety during an airborne pandemic",
        tech: "python,keras,resnet50,mobilenetv2",
        demoVideo: "https://www.youtube.com/watch?v=DMgSwCbm8EM",
        sourceCode: "https://github.com/jominjose14/FaceMask",
    },
    {
        name: "AI Personal Trainer",
        image: "personal-trainer.jpg",
        about: "An AI that monitors angles made during reps to ensure workout quality",
        tech: "python,mediapipe,opencv",
        demoVideo: "https://youtu.be/cy5hFlAnVS8",
        sourceCode: "https://github.com/jominjose14/AI-Personal-Trainer",
    },
    {
        name: "AI plays Flappy Bird",
        image: "neural.png",
        about: "An AI learns to play Flappy Bird through neuro-evolution",
        tech: "python,neuro-evolution,pygame",
        demoVideo: "https://youtu.be/2E4o2leGtTk",
        sourceCode: "https://github.com/jominjose14/AI-Flappy-Bird",
    },
    {
        name: "Melody",
        image: "melody.png",
        about: "A free online piano game that tests auditory and visual memory",
        tech: "html,css,javascript",
        webApp: "https://jominjose14.github.io/melody",
        sourceCode: "https://github.com/jominjose14/melody",
    },
    {
        name: "DrumKit 7.0",
        image: "drumkit.jpg",
        about: "A free online drumkit with configurable controls",
        tech: "html,css,javascript",
        webApp: "https://jominjose14.github.io/drumkit-7.0",
        sourceCode: "https://github.com/jominjose14/drumkit-7.0",
    },
    {
        name: "Lazy Bird",
        image: "lazybird.png",
        about: "An ice-themed remake of the Flappy Bird game",
        tech: "java,android,libgdx",
        demoVideo: "https://www.youtube.com/watch?v=VUkZguVlQK4",
        sourceCode: "https://github.com/jominjose14/LazyBird",
    },
    {
        name: "Muzik",
        image: "muzik.png",
        about: "A minimalistic yet stylish Android music player",
        tech: "java,android",
        demoVideo: "https://www.youtube.com/watch?v=xCsOT1tNK2k",
        sourceCode: "https://github.com/jominjose14/Muzik",
    },
    {
        name: "Tom vs Jerry",
        image: "tom-vs-jerry.jpg",
        about: "A Tom & Jerry themed tick-tac-toe game",
        tech: "java,android",
        demoVideo: "https://youtu.be/O-cqOHBODUI",
        sourceCode: "https://github.com/jominjose14/TicTacToeTomVSJerry",
    },
];
